
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-black
    rev: v20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-pytest
    rev: v5.4.3
    hooks:
    -   id: pytest
-   repo: https://github.com/pre-commit/mirrors-pytest
    rev: v5.4.3
    hooks:
    -   id: pytest-cov
