name: Lint

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x 

    - name: Install Make
      run: |
        sudo apt-get update
        sudo apt-get install make

    - name: Set up Environment File
      run: echo "${{ secrets.ENV_FILE }}" > .env


    - name: Install Dependencies
      run: |
        make install_linting_dependencies  

    - name: Run Linting
      run: |
        make lint_all  
